apiVersion: v1
kind: Service
metadata:
  name: advanced-app-service
spec:
  type: NodePort
  selector:
    app: advanced-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080