name: CI Pipeline

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  quality-and-security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java Runtime
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Initialize CodeQL (SAST)
        uses: github/codeql-action/init@v3
        with:
          languages: java

      # Manual Build to ensure CodeQL "sees" the com.example code
      - name: Build for CodeQL
        run: mvn clean compile -DskipTests

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Code Linting (Checkstyle)
        run: mvn checkstyle:check || echo "Linting finished with warnings"

      - name: Unit Tests
        run: mvn test

      - name: SCA (Snyk Dependency Scan)
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          LD_PRELOAD: ""

      - name: Build Final Artifact
        run: mvn package -DskipTests

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/advanced-app:${{ github.sha }} .

      - name: Image Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/advanced-app:${{ github.sha }}'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'